### ISSUE TITLE
Communication Problems

### ISSUE THREAD

**Issue by AldhairG** [NIVeriStandAdd-Ons/Instrument-Custom-Device#12]
Hello, i'm trying to use this Custom Device to control a Function Generator Agilent 33210A.
But I get the following error and I don't know if you could help me.
![console_ni_max_instruments](https://user-images.githubusercontent.com/38099182/39998366-28f2d790-5786-11e8-914d-576cfbeaa37c.PNG)
I'm using a PXIe System with a PXIE 8231 Ethernet Card.

I have the Function Generator connected by LAN to the (PXIE 8231)Ethernet Card, the Ethernet Card is connected to the PXIe Chassis. I don't know if i'm suppoused to configurate some parameters in order to get a succesfull connection.

This is the configuration that I have in this moment. I've tried everything that came to my mind but the Error keeps showing up.

![veristand_instr_gh_1](https://user-images.githubusercontent.com/38099182/39998890-c7bce6a8-5787-11e8-9a43-d7aba0a6efe6.PNG)
![veristand_instr_gh_2](https://user-images.githubusercontent.com/38099182/39998891-c7e9fa1c-5787-11e8-88ab-a5a1a465a0d6.PNG)
![veristand_instr_gh_3](https://user-images.githubusercontent.com/38099182/39998892-c81db744-5787-11e8-9c3c-83aa09bcb4af.PNG)
The following warning is completely irrelevant, right?
![veristand_instr_gh_4](https://user-images.githubusercontent.com/38099182/39999165-a16c8aa2-5788-11e8-822a-0a49a743bc13.PNG)

Thank you for taking your time.
Regards.

**Comment by AndrewHeim** [comment]
It looks to me like it is not completely configured.  That is likely the cause of the warnings and the errors.
The Command needs a definition, and you can tie it to your channels such as MetaData and MetaData 0.  You also need to give it instructions on how to parse the result.  

What goes in the command and parse fields depends on your instrument and its documentation. For example, most instruments respond to the SCPI command "*IDN" with their name, model number, and version information.  So that could be your command string (though in this case it would not use the MetaData channels you created).  On the Response page, the Response Format could be used to pull out a version string, for example.

There are more complete instructions in the documentation.  If you have specific questions about how something works, let us know.

**Comment by AldhairG** [comment]
Thank you very much for your answer.

Is there any possibility that I installed it wrong? Because I wasn't able to build the following:
But I think that is not a problem because I think this is just in case I want to use a CompactRIO Target. What do you think? 
![instruments_github](https://user-images.githubusercontent.com/38099182/40104800-8c46f8d2-58f1-11e8-9772-e514836b7c7a.PNG)

I get the same error after changing some configuration. 
![instruments_github_2](https://user-images.githubusercontent.com/38099182/40105075-3a4289d8-58f2-11e8-92f0-b4f7e205ad98.PNG)

I have a question. I think the problem is something related and I would like to read your opinion.
The connection with the controller of the PXI (PXIe-8821) is correct.

![instruments_github_4](https://user-images.githubusercontent.com/38099182/40105469-4c951866-58f3-11e8-9d44-c9ea179a71d6.PNG)

The Instrument(Agilent 33210A) is connected by LAN to an Ethernet Card(NI PXI-8231).
And the Ethernet Card is in the PXI Chassis.
The IP Address of the Ethernet Card(PXIE-8231) is 169.254.162.104
The IP Address of the Agilent 33210A is 169.254.2.20
The Subnet Mask is the same 255.255.0.0 

So in Veristand i have to write an IP Address and a Port.
I think I have to write the IP Address from the Agilent 33210A right?
In Port I have tried many standard Ports but I don't succeed.
![instruments_github_5](https://user-images.githubusercontent.com/38099182/40106273-9acfbc78-58f5-11e8-9066-200ab37fbed9.PNG)

**Comment by AndrewHeim** [comment]
I see.  It looks like target type is not necessarily the problem (though you will have to build the System Explorer build as well as your target type).  What I see is you don't have the dependencies all loaded.  It's hard to tell from here if you have the others on the list (check the readme) but you are definitely missing the Protections and Protocols classes.  You need to build them from their source (also listed in the readme):  https://github.com/NIVeriStandAdd-Ons/Instrument-Custom-Device-Classes

Once you build those, put them in the folders for the project you have now.  That will fix the "not found" error.  You shouldn't get any "not found" errors when you open the project.

Some of the other dependencies have links in the readme.  Most of the others are drivers or can be found on VIPM.

Typically if you are using these items from source here on github, it's assumed you're very comfortable with these sorts of things.  If you are, great.  If by chance you aren't, contact your local NI rep and we may be able to provide more assistance that way.

**Comment by AldhairG** [comment]
Thanks I solved the warnings and I checked all the dependecies and I apparently have them. But the error is still there.

> Typically if you are using these items from source here on github, it's assumed you're very comfortable with these sorts of things. If you are, great. If by chance you aren't, contact your local NI rep and we may be able to provide more assistance that way.

I'm not unfortunately.  I will contact them, thank you.
