### ISSUE TITLE
Trigger Channel

### ISSUE THREAD

**Issue by rdp137** [NIVeriStandAdd-Ons/Instrument-Custom-Device#13]
When I try to use the Veristand steps for Teststand (Set Channel) to trigger this custom device.  Teststand gets stuck.  My guess is that its related to the custom device trying to reset the trigger channel back to 0.  Is there anyway the trigger channel can just look for a value change so that it will trigger off of a message counter.

**Comment by eatondan** [comment]
I have run into this before. The TestStand steps allow you to set a timeout on the Write Channel function. Set the timeout to 0 and it will work.
