### ISSUE TITLE
Configuration Question

### ISSUE THREAD

**Issue by AldhairG** [NIVeriStandAdd-Ons/Instrument-Custom-Device#14]
Hi,
i'm sorry to post (maybe) such a easy question. It's really short so hopefully anyone can help me.
![unbenannt](https://user-images.githubusercontent.com/38099182/43204340-e1866786-9020-11e8-8d76-02c511c144a5.PNG)
I don't have any Idea of what should I enter as Port.

Where can I find this information ? Does it depend on something?
Thanks

**Comment by eatondan** [comment]
The port is for the device you are trying to interface with. There is typically a default value in the manual. I would start with that.
