### ISSUE TITLE
Hexadecimal numbers greater than 32 bits do not get interpreted properly

### ISSUE THREAD

**Issue by kavehv** [NIVeriStandAdd-Ons/Instrument-Custom-Device#2]
When scanning responses and formatting via strings, greater than 32bit responses do not get formatted properly.  Instead, they overflow the number.

**Comment by rdp137** [comment]
When I try to open the project, I get an error saying that I am missing Protocols.lvlibp and Protections.lvlibp.  What do I need to do?

**Comment by eatondan** [comment]
Confirmed.  This is a limitation of LabVIEW's Scan from String function.  I will document the limitation.
