### ISSUE TITLE
Selected discoverable port is not populated in the control properly

### ISSUE THREAD

**Issue by Sarci1** [NIVeriStandAdd-Ons/Instrument-Custom-Device#22]
In the RS-xxx to GPIB-ConvBox protocol selection, if the user attempts to use the discover port tool (i.e. magnifying glass). The user is able to see the list of available options on the selected target. However, if you choose to 'Use Selection' the selected port is not populated in the Port control.

**Comment by eatondan** [comment]
Fixed. Thank you!
