### ISSUE TITLE
Missing files when open project

### ISSUE THREAD

**Issue by mcdermmg** [NIVeriStandAdd-Ons/Instrument-Custom-Device#3]
When I try and open the project it can't find Protocols.lvlibp or Protections.lvibp, and then classes such as Protocol Parent.lvclass, VISA.lvclass etc.

**Comment by keprt** [comment]
You must first build the packed library (lvlibp) from LV project.

**Comment by mcdermmg** [comment]
Hi, thank you but I can't find the files in the source folder. The project is looking for Protocols.lvlibp or Protections.lvibp in the root of Source, and I can't find any classes such as RS-xxx.lvclass etc within the Source folders. The project thinks they are in the packed project. Do I need to download them from somewhere else?

**Comment by keprt** [comment]
Have you try https://github.com/NIVeriStandAdd-Ons/Instrument-Custom-Device-Classes ?

**Comment by mcdermmg** [comment]
Great, thank you I will do that.
