### ISSUE TITLE
Individual channels of array channels linked to seperate message variables 

### ISSUE THREAD

**Issue by rdp137** [NIVeriStandAdd-Ons/Instrument-Custom-Device#6]
It would be helpful if I could create a channel array and then when I build my command or response message to be able to link my message linkages to individual elements of my channel array..

As an example I want to create two channel arrays, "com" and "data" .  Then my command/response message can be
[com1][data1][com2][data2][com3][data3]......

**Comment by eatondan** [comment]
I do not plan to add this as a feature.
