### ISSUE TITLE
XML Config file

### ISSUE THREAD

**Issue by rdp137** [NIVeriStandAdd-Ons/Instrument-Custom-Device#7]
For certain instances the XML Config file does not add the version tag which causes the following error.

Error 537534 occurred at gxml_GetTypeDefVersion.vi when I try to import.

Not sure it its related to higher number of channels

**Comment by eatondan** [comment]
I have seen this as well.  I have moved to a new way of import/exporting that is more re-usable with my other addons.  It should also solve this issue.
