### ISSUE TITLE
Trigger Channel

### ISSUE THREAD

**Issue by rdp137** [NIVeriStandAdd-Ons/Instrument-Custom-Device#9]
Do you have any interest in making the trigger type select-able, making it state based like it is now or triggering off of a counter change?

**Comment by huazy23** [comment]
There is a VI broken error in "command engine read async FIFOs.vi" .

**Comment by eatondan** [comment]
rdp137 - You can do this yourself using a labVIEW model.

huazy23 - I recently updated a bunch of addons to use a more common base framework/API.  The required APIs are listed in the Readme.  It should have gotten rid of the missing items (assuming you install everything listed in the Readme).
